// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHpVlAETGhQ5FEGbxRwwysxYIk_YmVKtA',
    appId: '1:862618163962:web:e7b080d8321c5701e8c743',
    messagingSenderId: '862618163962',
    projectId: 'worldcapitaldb',
    authDomain: 'worldcapitaldb.firebaseapp.com',
    storageBucket: 'worldcapitaldb.appspot.com',
    measurementId: 'G-9WMHMDTHSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzbZZQ_snKE17R1wIFJE0Ze2WJkIvZuOg',
    appId: '1:862618163962:android:60de22fac51467a3e8c743',
    messagingSenderId: '862618163962',
    projectId: 'worldcapitaldb',
    storageBucket: 'worldcapitaldb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnUNaOwfeJQJnW4ICowjt8VMZwIr3psg',
    appId: '1:862618163962:ios:75f051b6666539e2e8c743',
    messagingSenderId: '862618163962',
    projectId: 'worldcapitaldb',
    storageBucket: 'worldcapitaldb.appspot.com',
    androidClientId: '862618163962-v88p08p4nrjvqoipkuvklct7rgpoej80.apps.googleusercontent.com',
    iosClientId: '862618163962-81742jcgnpmvemgu25nsjdd6gh1nut4j.apps.googleusercontent.com',
    iosBundleId: 'com.camugames.worldCapitals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnUNaOwfeJQJnW4ICowjt8VMZwIr3psg',
    appId: '1:862618163962:ios:75f051b6666539e2e8c743',
    messagingSenderId: '862618163962',
    projectId: 'worldcapitaldb',
    storageBucket: 'worldcapitaldb.appspot.com',
    androidClientId: '862618163962-v88p08p4nrjvqoipkuvklct7rgpoej80.apps.googleusercontent.com',
    iosClientId: '862618163962-81742jcgnpmvemgu25nsjdd6gh1nut4j.apps.googleusercontent.com',
    iosBundleId: 'com.camugames.worldCapitals',
  );
}
